<a href="https://colab.research.google.com/github/SmiejaGrzegorz/data_science/blob/main/ds_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World !!!")

### NumPy

Podstawy


In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
a = np.full(shape=(3, 3), fill_value=5, dtype='int')
print(a)

In [ ]:
b = np.arange(1, 21, 2)
print(b)
print('\n')
print(b.reshape(-1, 2))
print('\n')
b.dtype

In [ ]:
c = np.zeros(shape=(4, 6), dtype='int')
print(c)
print('\n')
print(c.reshape(6, -1))

In [ ]:
a = np.full(shape=(1, 5), fill_value=2, dtype=int)
b = np.full(shape=(1, 5), fill_value=5, dtype=int)
print(a)
print(b)

In [ ]:
a + b

In [ ]:
c = np.array([1, 2, 3, 4])
d = np.array([9, 8, 7, 6])
print(c)
print(d)

In [ ]:
c + d

In [ ]:
c * d

In [ ]:
A1 = np.array([[1, 3], [4,5]])
A2 = np.array([[3, 3], [2, 1]])
print(A1)
print(A2)

In [ ]:
A1 * A2

array([[3, 9],
       [8, 5]])

###mnożenie macierzy

In [ ]:
np.dot(A1, A2)

In [39]:
a1 = np.random.randint(10, size=(2, 2))
a2 = np.random.randint(10, size=(2, 2))

In [40]:
print(a1, '\n')
print(a2)

[[7 0]
 [1 9]] 

[[9 0]
 [4 7]]


In [41]:
np.dot(a1, a2)

array([[63,  0],
       [45, 63]])

In [42]:
a1.dot(a2)

array([[63,  0],
       [45, 63]])

In [ ]:
a2.dot(a1)

In [ ]:
print(a1 @ a2)
print(a2 @ a1)

### generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)
np.random.randn(1, 2) #losowy rozkład normalny

In [ ]:
np.random.randn(1, 2)

In [ ]:
np.random.rand(4, 3) #zwraca losowową liczbe z przedziału 0 - 1

In [ ]:
np.random.randint(low=10, high=100) #zwraca losową liczbe z przedziału 10 - 100(99)

In [ ]:
np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9]) #zwraca losowy element z podanej listy

In [ ]:
np.random.choice(['jebac', 'stare', 'baby', 'prądem'])

In [78]:
data = np.arange(1, 11)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.random.shuffle(data) #shuffle miesza, zmienia kolejność elementów
data

array([2, 5, 3, 1, 6, 0, 8, 7, 4, 9])

### podstawowe funckje

In [ ]:
np.exp(data) #zwraca exponent(wykładnik)

In [ ]:
data1 = np.array([1, 2, 3])
x = np.exp(data1)
x

In [ ]:
np.sqrt(1) #zwraca pierwiastek kwadratowy z podanego elementu (zawssze float)

In [ ]:
np.all(data) #iteruje po elementach i zwraca True/False 

In [ ]:
print(np.any([1, 2, 3])) #zwraca True/False jeśli jakikolwiek elemetn jest True
print(np.any([0, 0, 0]))

In [ ]:
a1 = np.random.randn(5)
a1

In [ ]:
np.argmax(a1) #zwraca INDEKS(np. a1[1], a1[0]) największego elementu w tym przypdaku w lisćie

In [ ]:
a1[np.argmax(a1)] #możliwość zwrócenia wyniku funkcji np.argmax(); robimy wycinek

In [ ]:
np.argmin(a1) #odwrotność np.argmax(); zwraca najmniejszy element

In [ ]:
a1[np.argmin(a1)]

In [ ]:
np.argsort(a1) #sortuje zwracając indeksy elementów (sortowanie rosnąco); działa przy klasyfikacji wieloklasowej

In [ ]:
np.max(a1) #zwraca największą wartość

In [ ]:
np.min(a1) #zwraca najmniejszą wartość

In [ ]:
np.mean(a1) #zwraca średnią wszystkich wartości

In [ ]:
np.median(a1) #zwraca medianę

In [ ]:
np.std(a1) #zwraca odchylenie standardowe

### indeksowanie

In [8]:
data = np.arange(1, 21)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**A[indeks], A[start:stop], A[:stop], A[start:]**

In [9]:
data[3] #wycinek tablicy

4

In [10]:
data = data.reshape(4, 5)
data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
data[0][1] #zwraca podanym indeks po zastosowaniu np.reshape()

2

In [13]:
data[:, 2] #data[:, indeks kolumny] - taki zapis zwraca kolumne z podanym indeksem

array([ 3,  8, 13, 18])

In [15]:
data[2, 3] #zwraca dokładny element data[indeks wiersza, indeks kolumny]

14

In [18]:
data[2:4, 2:4] #zaraca wiekszy fragment tablicy 

array([[13, 14],
       [18, 19]])

In [ ]:
data[0, 4] = 88 #istnieje możliwość zastąpienia wycieętego elementu innym
data

### iteracja po tablicach, zmiania rozmiaru oraz maski logiczne

iteracja po tablicach

In [ ]:
for el in data: #iteracja co tablicy w tym przypadku: data
  print(el)

In [ ]:
for item in data: #iteracja po wybranej kolumnie
  print(item[1])

In [ ]:
data[0, 4] = 5
data

In [ ]:
for item in data.flat: #dzięki funkcji np.flat możemy iterować po każdym elemencie
  print(item)

zmiana rozmiaru tablic

In [ ]:
data.reshape(-1, 2) #zmiania postac tablicy jak wyżej

In [ ]:
data.ravel() #powtót do płąskiej postaci tablicy; odwrotność funkcji .reshape()

In [ ]:
data

In [ ]:
data.T #transponowanie; zaminia wiersza na kolumne, kolumny na wiersz

maski logiczne

In [36]:
A = np.arange(-10, 10, 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [38]:
A > 0 #sprawdza czy wartości tablicy są ujemne zwracając True/False

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
A[A > 0] #dzięki tej masce wycinamy wartości większe od zera

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [40]:
A[A < 0] # działanie odwrotne  do A[A > 0]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5])

In [41]:
A[A == 0]

array([0.])

In [43]:
A[np.bitwise_and(A > -5, A < 5)] #zastępuje and

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
A